
env:
  global:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
jobs:
  include:
    - language: rust
      script: echo "npm test temporarily disabled"
      before_install:
        - sudo wget https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -O ~/.nvm/nvm.sh
        - source ~/.nvm/nvm.sh
        - . "$NVM_DIR/nvm.sh"
        - nvm install 14.5.0  
        - node --version
        - npm i -g typescript
        - npm install -g aws-cdk
        - npm i
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      before_script:
        - cd lambda
        - cargo install cross
        - cross build --target aarch64-unknown-linux-gnu --release
        - cd target/aarch64-unknown-linux-gnu/release
        - mkdir lambda
        - cp bootstrap lambda
        - ls
        - cd lambda
        - ls
        - cd ../../../../../
        - ls
        - mkdir ~/.aws/
        - touch ~/.aws/credentials
        - echo -e "[default]\n $AWS_ACCESS_KEY_ID \n $AWS_SECRET_ACCESS_KEY \n region=us-east-1" >> ~/.aws/credentials
        - cdk bootstrap
        - cdk deploy --require-approval never

